---
- name: Install Celery
  pip: name="{{ item.name }}" version={{ item.version }} state=present
  with_items:
    - { name: "celery[redis]", version: "{{ celery_version }}" }
    - { name: "django-celery", version: "{{ djcelery_version }}" }
    - { name: "flower", version: "{{ flower_version }}" }
