---
- name: Install application Python dependencies for development and test
  pip: chdir={{ app_home }}/requirements requirements={{ item }}.txt
  with_items:
    - development
    - test
  notify:
    - Restart mmw-app

- name: Install Firefox for UI tests
  apt: pkg=firefox="3*" state=present

- name: Install Xvfb for JavaScript tests
  apt: pkg=xvfb="2:1.15.1*" state=present
