---
dependencies:
  - { role: "model-my-watershed.base" }
  - { role: "azavea.nodejs", nodejs_version: "{{ tiler_nodejs_version }}", nodejs_npm_version: "{{ tiler_nodejs_npm_version }}" }
  - { role: "model-my-watershed.nginx", nginx_delete_default_site: True }
