envdir_home: "/etc/mmw.d/env"

envdir_config:
  MMW_DB_NAME: "{{ postgresql_database }}"
  MMW_DB_USER: "{{ postgresql_username }}"
  MMW_DB_PASSWORD: "{{ postgresql_password }}"
  MMW_DB_HOST: "{{ postgresql_host }}"
  MMW_DB_PORT: "{{ postgresql_port }}"
  MMW_CACHE_HOST: "{{ redis_host }}"
  MMW_CACHE_PORT: "{{ redis_port }}"
  MMW_TILER_HOST: "{{ tiler_host }}"
  MMW_GEOPROCESSING_CACHE: "{{ geop_cache_enabled }}"
  MMW_GEOPROCESSING_HOST: "{{ geop_host }}"
  MMW_GEOPROCESSING_PORT: "{{ geop_port }}"
  MMW_GEOPROCESSING_VERSION: "{{ geop_version }}"
  MMW_GEOPROCESSING_TIMEOUT: "{{ geop_timeout }}"
  MMW_GEOPROCESSING_BUCKET: "{{ geop_bucket }}"
  MMW_ITSI_CLIENT_ID: "{{ itsi_client_id }}"
  MMW_ITSI_SECRET_KEY: "{{ itsi_secret_key }}"
  MMW_ITSI_BASE_URL: "{{ itsi_base_url }}"
  MMW_CONCORD_SECRET_KEY: "{{ concord_secret_key }}"
  MMW_HYDROSHARE_CLIENT_ID: "{{ hydroshare_client_id }}"
  MMW_HYDROSHARE_SECRET_KEY: "{{ hydroshare_secret_key }}"
  MMW_HYDROSHARE_BASE_URL: "{{ hydroshare_base_url }}"
  MMW_SRAT_CATCHMENT_API_URL: "{{ srat_catchment_api_url }}"
  MMW_SRAT_CATCHMENT_API_KEY: "{{ srat_catchment_api_key }}"
  MMW_CLIENT_APP_USER_PASSWORD: "{{ client_app_user_password }}"
  MMW_STACK_COLOR: "{{ stack_color }}"
  MMW_TILECACHE_BUCKET: "{{ tilecache_bucket_name }}"
  MMW_STACK_TYPE: "{{ stack_type }}"
  MMW_ENABLED_FEATURES: "{{ enabled_features }}"

  ROLLBAR_SERVER_SIDE_ACCESS_TOKEN: "Unknown"
