envdir_home: "/etc/mmw.d/env"

envdir_config:
  MMW_DB_NAME: "{{ postgresql_database }}"
  MMW_DB_USER: "{{ postgresql_username }}"
  MMW_DB_PASSWORD: "{{ postgresql_password }}"
  MMW_DB_HOST: "{{ postgresql_host }}"
  MMW_DB_PORT: "{{ postgresql_port }}"
  MMW_STATSD_HOST: "{{ statsite_host }}"
  MMW_CACHE_HOST: "{{ redis_host }}"
  MMW_CACHE_PORT: "{{ redis_port }}"
  MMW_TILER_HOST: "{{ tiler_host }}"
  MMW_GEOPROCESSING_HOST: "{{ geop_host }}"
  MMW_ITSI_CLIENT_ID: "{{ itsi_client_id }}"
  MMW_ITSI_SECRET_KEY: "{{ itsi_secret_key }}"
  MMW_ITSI_BASE_URL: "{{ itsi_base_url }}"
  MMW_STACK_COLOR: "{{ stack_color }}"
  MMW_TILECACHE_BUCKET: "{{ tilecache_bucket_name }}"
