---
- name: Configure application
  copy: content="{{ item.value }}"
        dest="{{ envdir_home }}/{{ item.key }}"
        owner=root
        group=mmw
        mode=0750
  with_dict: app_config
  notify:
    - Restart Celery
