---
- { include: configuration.yml }
- { include: app.yml, when: "['packer'] | is_in(group_names)" }
- { include: dependencies.yml }
- { include: celery-user.yml }
- { include: celery-service.yml }
- { include: flower.yml }
