---
- name: Create service account for application
  user: name=mmw
        system=yes
        home=/var/lib/mmw
        shell=/bin/false
        state=present

- name: Add Vagrant user to the mmw group
  user: name=vagrant
        append=yes
        group=mmw
        state=present
  when: "['development', 'test'] | some_are_in(group_names)"

- name: Add Ubuntu user to the mmw group
  user: name=ubuntu
        append=yes
        group=mmw
        state=present
  when: "['packer'] | is_in(group_names)"

- name: Create configuration file directory
  file: path={{ tiler_config_home }}
        owner=root
        group=mmw
        mode=0750
        state=directory

- name: Configure application
  copy: content={{ item.content }}
        dest={{ tiler_config_home }}/{{ item.file }}
        owner=root
        group=mmw
        mode=0750
  with_items: tiler_config
  notify:
    - Restart mmw-tiler

- name: Configure service definition
  template: src=upstart-mmw-tiler.conf.j2 dest=/etc/init/mmw-tiler.conf
  notify:
    - Restart mmw-tiler
