---
- name: Configure Nginx site
  template: src=nginx-tiler.conf.j2
            dest=/etc/nginx/sites-available/mmw-tiler.conf
  notify:
    - Restart Nginx

- name: Enable Nginx site
  file: src=/etc/nginx/sites-available/mmw-tiler.conf
        dest=/etc/nginx/sites-enabled/mmw-tiler
        state=link
  notify:
    - Restart Nginx

- name: Enable nginx service
  service: name=nginx.service enabled=yes
