- src: azavea.ntp
  version: 0.1.1
- src: azavea.pip
  version: 2.0.0
- src: azavea.nodejs
  version: 0.3.0
- src: azavea.git
  version: 0.1.0
- src: azavea.nginx
  version: 0.3.1
- src: azavea.daemontools
  version: 0.1.0
- src: azavea.postgresql-support
  version: 0.3.0
- src: azavea.postgresql
  version: 1.0.0
- src: azavea.postgis
  version: 0.3.0
- src: azavea.python
  version: 0.1.0
- src: azavea.redis
  version: 0.1.0
- src: azavea.phantomjs
  version: 0.1.0
- src: azavea.build-essential
  version: 0.1.0
- src: azavea.java
  version: 0.6.2
- src: azavea.docker
  version: 4.0.0
- src: azavea.papertrail
  version: 2.0.0
