- src: azavea.ntp
  version: 0.1.1
- src: azavea.nodejs
  version: 0.3.0
- src: azavea.yarn
  version: 0.1.0
- src: azavea.git
  version: 0.1.0
- src: azavea.nginx
  version: 1.0.0
- src: azavea.daemontools
  version: 0.1.0
- src: azavea.postgresql
  version: 1.0.0
- src: azavea.postgis
  version: 0.3.0
- src: azavea.redis
  version: 0.1.0
- src: azavea.build-essential
  version: 0.1.0
- src: azavea.java
  version: 0.7.0
- src: azavea.docker
  version: 6.0.0
